name: hello-world
on:
  push:
    branches: ["stage"]
env:
  TEXT: "Roberto Carlos Morales Herrera"

jobs:
  print:
    runs-on: ubuntu-latest 

    steps:
      - name: print-to-screen
        run: echo "Hello World! ${{env.TEXT}} - ${{secrets.SECRET_NAME}}"

      - name: El job funciono?
        if: ${{ success() }}
        run: echo "Job Succeded!!!"

      - name: El job fallo?
        if: ${{ failure() }}
        run: echo "Job Fails :("